/**
* @author Jakub Bubak
* @date 15.03.2024
*/

#ifndef KALMAN_ELECTRONICS_MASTER_V3_BRIDGE_H
#define KALMAN_ELECTRONICS_MASTER_V3_BRIDGE_H

/**
 * @brief Initialize function, called before loop in main.c file
 * */
void Init();

/**
 * @brief Function called in main loop in main.c file
 * */
void Loop();

/**
 * @brief Error handler function called in C error handler generated by CubeMX
* */
void ErrorHandler();

/**
 * @brief Callback function called in C SysTick in stm32g4xx_it.c, function is called before SysTick increase
 * */
void SysTickCallback();


#endif //KALMAN_ELECTRONICS_MASTER_V3_BRIDGE_H
