#ifndef KALMAN_ELECTRONICS_MASTER_V3_UART_PACKET_HANDLER_H
#define KALMAN_ELECTRONICS_MASTER_V3_UART_PACKET_HANDLER_H

#include "FreeRTOS.h"
#include "task.h"

#define UART_HANDLER_TASK_PRIORITY 7
#define UART_HANDLER_TASK_STACK_SIZE 512
extern StaticTask_t UARTHandlerTaskBuffer;
extern StackType_t UARTHandlerTaskStack[UART_HANDLER_TASK_STACK_SIZE];

void UARTHandler_Task(void *argument);

#endif //KALMAN_ELECTRONICS_MASTER_V3_UART_PACKET_HANDLER_H
