#ifndef KALMAN_ELECTRONICS_MASTER_V3_CAN_PACKET_HANDLER_H
#define KALMAN_ELECTRONICS_MASTER_V3_CAN_PACKET_HANDLER_H

#include "FreeRTOS.h"
#include "task.h"

#define CAN_HANDLER_TASK_PRIORITY 10
#define CAN_HANDLER_TASK_STACK_SIZE 256
extern StaticTask_t CANHandlerTaskBuffer;
extern StackType_t CANHandlerTaskStack[CAN_HANDLER_TASK_STACK_SIZE];

void CANHandler_Task(void *argument);

#endif //KALMAN_ELECTRONICS_MASTER_V3_CAN_PACKET_HANDLER_H
